try adding error message

diff --git a/.github/workflows/integration_test.yml b/.github/workflows/integration_test.yml
--- a/.github/workflows/integration_test.yml
+++ b/.github/workflows/integration_test.yml
@@ -40,7 +40,7 @@ jobs:
       - name: Run Integration tests
         run: |
           Rscript -e "testthat::test_dir('tests/testthat/', reporter = c('fail', 'progress','summary'), stop_on_failure=TRUE, stop_on_warning=FALSE)"
-          if errorlevel 1 exit 1
+          if errorlevel 1 echo "::error:: Integration tests failed" && exit 1
         shell: cmd
         continue-on-error: false
         env:
@@ -49,7 +49,7 @@ jobs:
       - name: Check input spreadsheet
         run: |
           Rscript -e "rmarkdown::render('validation_report.Rmd', 'html_document', params=list(inputFile='config/model_inputs.xlsx', outputDir='log'), output_dir='log')"
-          if errorlevel 1 exit 1
+          if errorlevel 1 "::error:: Validate Input failed" && exit 1
         shell: cmd
         continue-on-error: false
       - uses: actions/upload-artifact@v3
